// <auto-generated />
namespace Peluqueria3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeusersextype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeusersextype));
        
        string IMigrationMetadata.Id
        {
            get { return "201603122342332_change-user-sex-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
